language: android
jdk: oraclejdk8
sudo: required
dist: precise
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
  - ./android/gradlew assembleRelease --stacktrace --no-daemon
after_script:
  - ./android/gradlew crashlyticsUploadDistributionRelease
before_install:
  - chmod +x ./android/gradlew
  - openssl aes-256-cbc -K $encrypted_c0801aa05af4_key -iv $encrypted_c0801aa05af4_iv -in ./android/app/rn-sample-key.keystore.enc -out rn-sample-key.keystore -d
branches:
  only:
  - master
